# services:
#   frontend:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#       args:
#         - VITE_SUPABASE_URL=${SUPABASE_URL}
#         - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
#     ports:
#       - "80:80"
#     environment:
#       - VITE_SUPABASE_URL=${SUPABASE_URL}
#       - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - PORT=3000

# networks:
#   default:
#     name: toolkit_network
#     driver: bridge

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      # - "80:80"
      - "5173:5173"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload
    volumes:
      - ./frontend:/app  # Mount the frontend directory
      - /app/node_modules  # Anonymous volume for node_modules
    command: npm run dev -- --host 0.0.0.0  # Run in development mode

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/app  # Mount the backend directory
      - /app/node_modules  # Anonymous volume for node_modules

networks:
  default:
    name: toolkit_network
    driver: bridge